### ISSUE TITLE
ReadTheDocs link is not working

### ISSUE THREAD

**Issue by Timple** [aliasrobotics/ros1_fuzzer#11]

**Comment by vmayoral** [comment]
Thanks for reporting @Timple. We have decided to move support of this tool to a centralized toolset instead, won't be maintaining it any further unfortunately.

I've updated the README.md. If you need past details on usage refer to the [sphinx docs](https://github.com/aliasrobotics/ros1_fuzzer/tree/master/docs) we created at the time. You'll see that I'll archive the repo, feel free to contact me personally if you need additional information.
